[package]
name = "q1tsim-derive"
version = "0.1.0"
authors = ["Gé Vissers <ge@q1t.nl>"]
description="Derive macros for the q1tsim crate."
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = "0.14"
quote = "0.6"
